# Numpy 实验

In [1]:
import numpy as np

### （1）用0~19的数字生成(4,5)的数组命名为a, 查看a的维度、轴的个数、元素的总个数、每个元素的字节大小。

In [2]:
a = np.arange(0,20).reshape(4,5) # 0-19生成（4，5）的数组a
print("a的维度:",a.shape)  
print("a的轴个数:",a.ndim) 
print("a的元素总个数:",a.size)  
print("a每个元素的子节大小:",a.itemsize) 

a的维度: (4, 5)
a的轴个数: 2
a的元素总个数: 20
a每个元素的子节大小: 4


### （2）创建元素为1,2,3,4的(2,2)的数组 b，查看b中元素类型。

In [3]:
b = np.arange(1,5).reshape(2,2)
b.dtype

dtype('int32')

### （3）创建一个全1的（4,4）的数组c，创建一个内容随机的(3,2)数组d，并打印d。

In [4]:
c = np.ones(shape=(4,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
d = np.random.random((3,2))
d

array([[0.12768664, 0.85792323],
       [0.0314189 , 0.91467993],
       [0.77474507, 0.35641596]])

### （4）用0~11的数，创建一个3*4的数组n1，计算每一列的和；计算每一行的最小值。


In [6]:
n1 = np.arange(0,12).reshape(3,4)
n1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.sum(n1,axis=0) # 每列的和

array([12, 15, 18, 21])

In [8]:
np.min(n1,axis=1) # 每行的min

array([0, 4, 8])

### （5）生成一个3个元素的数组n2,通过常用函数计算n2的平方根和标准差。

In [9]:
n2 = np.random.random(3)
print(n2)
print(np.sqrt(n2)) # 平方根
print(np.std(n2)) # 标准差

[0.50110699 0.48999255 0.85012241]
[0.70788911 0.69999468 0.92202083]
0.16720872220106892


### （6）生成一个9个（可以从0~8）元素的数组n3,计算每个元素的平方；取出位置2的元素；取出位置2至5之间的元素。


In [10]:
n3 = np.arange(0,9)
print(np.square(n3))
print(n3[2])
print(n3[2:6])

[ 0  1  4  9 16 25 36 49 64]
2
[2 3 4 5]


### （7）随机生成2个3*3的数组n4和n5，将n4和n5进行垂直合并形成n6;将n4和n5进行水平合并形成n7。

In [11]:
n4 = np.random.random((3,3))
n4

array([[0.94043187, 0.5395579 , 0.18411719],
       [0.67037421, 0.59593074, 0.11731589],
       [0.41768002, 0.73671782, 0.29775028]])

In [12]:
n5 = np.random.random((3,3))
n5

array([[0.90355236, 0.96031412, 0.60958814],
       [0.81005751, 0.62944152, 0.24066393],
       [0.38171292, 0.24505742, 0.0332577 ]])

In [13]:
n6 = np.concatenate((n4,n5),axis = 0)
n6

array([[0.94043187, 0.5395579 , 0.18411719],
       [0.67037421, 0.59593074, 0.11731589],
       [0.41768002, 0.73671782, 0.29775028],
       [0.90355236, 0.96031412, 0.60958814],
       [0.81005751, 0.62944152, 0.24066393],
       [0.38171292, 0.24505742, 0.0332577 ]])

In [14]:
n7 = np.concatenate((n4,n5),axis = 1)
n7

array([[0.94043187, 0.5395579 , 0.18411719, 0.90355236, 0.96031412,
        0.60958814],
       [0.67037421, 0.59593074, 0.11731589, 0.81005751, 0.62944152,
        0.24066393],
       [0.41768002, 0.73671782, 0.29775028, 0.38171292, 0.24505742,
        0.0332577 ]])

### （8）创建一个2行3列的零矩阵命名为z,将z的2行3列的位置值置成1。

In [15]:
z = np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
z[1][2] = 1
z

array([[0., 0., 0.],
       [0., 0., 1.]])

### （9）生成4*4的对角矩阵，以[1,2,3,4]为对角线,其他位置用0填充，命名为z1 。

In [17]:
z1 = np.diag([1,2,3,4])
z1

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### （10）用0~8的数，创建成3*3的矩阵，命名为z2;用随机数，创建4*4的矩阵，命名为z3。

In [18]:
z2 = np.arange(0,9).reshape(3,3)
z2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
z3 = np.random.random((4,4))
z3

array([[0.65474862, 0.20677777, 0.25388384, 0.59509623],
       [0.23233508, 0.25160897, 0.78588671, 0.64651159],
       [0.52050226, 0.54459053, 0.68350352, 0.16470752],
       [0.44868952, 0.26847468, 0.8255424 , 0.89054901]])

### （11）读取iris数据集中的数据。 

In [20]:
data = np.loadtxt('iris.csv',delimiter=',',skiprows = 1,usecols=(0,1,2,3))
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

### （12）获取数据中的花萼长度数据。

In [21]:
sepal_length = data[:,0]

### （13）对花萼长度数据进行排序。

In [22]:
np.sort(sepal_length)

array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

### （14）对花萼长度数据进行去重。 

In [23]:
np.unique(sepal_length)

array([4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9])

### （15）对花萼长度数据进行求和。 

In [24]:
np.sum(sepal_length)

876.5

### （16）对花萼长度数据进行求均值。 

In [25]:
np.average(sepal_length)

5.843333333333334

### （17）对花萼长度数据求累计和。


In [26]:
np.cumsum(sepal_length)

array([  5.1,  10. ,  14.7,  19.3,  24.3,  29.7,  34.3,  39.3,  43.7,
        48.6,  54. ,  58.8,  63.6,  67.9,  73.7,  79.4,  84.8,  89.9,
        95.6, 100.7, 106.1, 111.2, 115.8, 120.9, 125.7, 130.7, 135.7,
       140.9, 146.1, 150.8, 155.6, 161. , 166.2, 171.7, 176.6, 181.6,
       187.1, 192. , 196.4, 201.5, 206.5, 211. , 215.4, 220.4, 225.5,
       230.3, 235.4, 240. , 245.3, 250.3, 257.3, 263.7, 270.6, 276.1,
       282.6, 288.3, 294.6, 299.5, 306.1, 311.3, 316.3, 322.2, 328.2,
       334.3, 339.9, 346.6, 352.2, 358. , 364.2, 369.8, 375.7, 381.8,
       388.1, 394.2, 400.6, 407.2, 414. , 420.7, 426.7, 432.4, 437.9,
       443.4, 449.2, 455.2, 460.6, 466.6, 473.3, 479.6, 485.2, 490.7,
       496.2, 502.3, 508.1, 513.1, 518.7, 524.4, 530.1, 536.3, 541.4,
       547.1, 553.4, 559.2, 566.3, 572.6, 579.1, 586.7, 591.6, 598.9,
       605.6, 612.8, 619.3, 625.7, 632.5, 638.2, 644. , 650.4, 656.9,
       664.6, 672.3, 678.3, 685.2, 690.8, 698.5, 704.8, 711.5, 718.7,
       724.9, 731. ,

### （18）对花萼长度数据求标准差。

In [27]:
np.std(sepal_length)

0.8253012917851409

### （19）对花萼长度数据求方差 。 

In [28]:
np.var(sepal_length)

0.6811222222222223

### （20）对花萼长度数据求最大值、最小值

In [29]:
max_sepal_length = np.max(sepal_length)
min_sepal_length = np.min(sepal_length)
print(max_sepal_length,min_sepal_length)

7.9 4.3


# Pandas实验

In [30]:
import pandas as pd

### 1 将数据读取为dataframe类型，命名为df

In [31]:
df = pd.read_csv("flight.csv")

### 2 查看数据的形状[了解数据有多少行、多少列]

In [32]:
df.shape

(174, 14)

### 3 查看数据的最开始的7条数据和尾部的3条数据

In [33]:
df.head(7)

date  hour  minute     dep     arr  dep_delay  arr_delay carrier  \
0  2011/12/1  14.0    31.0  1431.0  1730.0       -4.0       -9.0      XE   
1  2011/12/1  21.0    15.0  2115.0  2229.0      -10.0       -7.0      XE   
2  2011/12/1  10.0    47.0  1047.0  1429.0       20.0       17.0      XE   
3  2011/12/1  19.0    24.0  1924.0  2234.0       -1.0        1.0      XE   
4  2011/12/1   7.0    18.0   718.0  1105.0       -2.0       -8.0      XE   
5  2011/12/1  20.0    18.0  2018.0  2200.0       -2.0       -9.0      XE   
6  2011/12/2  21.0    20.0  2120.0  2230.0       -5.0       -6.0      XE   

   flight dest   plane  cancelled   time  dist  
0    4319  SAV  N11121          0  104.0   851  
1    4342  LRD  N11107          0   50.0   301  
2    4434  RIC  N11113          0  146.0  1157  
3    4525  SAV  N11106          0  105.0   851  
4    4602  DTW  N11121          0  139.0  1075  
5    4674  BNA  N11121          0   82.0   657  
6    4342  LRD  N11113          0   53.0   301

In [34]:
df.tail(3)

date  hour  minute     dep     arr  dep_delay  arr_delay carrier  \
171  2011/12/30  11.0    14.0  1114.0  1141.0        9.0        6.0      XE   
172  2011/12/30  18.0    31.0  1831.0  2145.0       16.0        9.0      XE   
173  2011/12/31  14.0     8.0  1408.0  1705.0        2.0       -1.0      XE   

     flight dest   plane  cancelled   time  dist  
171    4323  HOB  N11107          0   73.0   501  
172    4634  CLT  N11121          0  116.0   912  
173    4433  TYS  N11107          0   98.0   771

### 4 查看数据的各字段的类型

In [35]:
df.dtypes

date          object
hour         float64
minute       float64
dep          float64
arr          float64
dep_delay    float64
arr_delay    float64
carrier       object
flight         int64
dest          object
plane         object
cancelled      int64
time         float64
dist           int64
dtype: object

### 5 查看数据是否有缺失值

In [36]:
df.isna().any()

date         False
hour          True
minute        True
dep           True
arr           True
dep_delay     True
arr_delay     True
carrier      False
flight       False
dest         False
plane        False
cancelled    False
time          True
dist         False
dtype: bool

### 6 如果有缺失值，进行补0操作

In [37]:
filled = df.fillna(0)
filled.isna().any() # na全被填充

date         False
hour         False
minute       False
dep          False
arr          False
dep_delay    False
arr_delay    False
carrier      False
flight       False
dest         False
plane        False
cancelled    False
time         False
dist         False
dtype: bool

### 7 从df中按字段取出‘ date’’dist’和‘ flight’形成新的df1

In [38]:
df1 = df[['date','dist','flight']]
df1.head()

date  dist  flight
0  2011/12/1   851    4319
1  2011/12/1   301    4342
2  2011/12/1  1157    4434
3  2011/12/1   851    4525
4  2011/12/1  1075    4602

### 8 从df中按位置选取行为3和4，列为0,1的数据形成新的df2

In [39]:
df2 = df.iloc[3:5,[0,1]]
df2

date  hour
3  2011/12/1  19.0
4  2011/12/1   7.0

### 9 在df中添加一列‘ low_dest’，内容是‘ dest’这列的字符串的小写形式

In [40]:
df['low_dest'] = df['dest'].map(lambda x:x.lower())
df[['low_dest','dest']].head()

low_dest dest
0      sav  SAV
1      lrd  LRD
2      ric  RIC
3      sav  SAV
4      dtw  DTW

### 10 从df中选取‘ dist’大于1000并且小于1200的数据作为一个新的df3

In [41]:
df3 = df[(df['dist'] > 1000) & (df['dist'] <1200)]
df3.head()

date  hour  minute     dep     arr  dep_delay  arr_delay carrier  \
2   2011/12/1  10.0    47.0  1047.0  1429.0       20.0       17.0      XE   
4   2011/12/1   7.0    18.0   718.0  1105.0       -2.0       -8.0      XE   
10  2011/12/2   7.0    13.0   713.0  1058.0       -2.0       -6.0      XE   
14  2011/12/3  19.0     1.0  1901.0  2230.0       -1.0      -14.0      XE   
16  2011/12/4  16.0     8.0  1608.0  2004.0       18.0       40.0      XE   

    flight dest   plane  cancelled   time  dist low_dest  
2     4434  RIC  N11113          0  146.0  1157      ric  
4     4602  DTW  N11121          0  139.0  1075      dtw  
10    4501  PIT  N11107          0  146.0  1117      pit  
14    4509  RIC  N11113          0  134.0  1157      ric  
16    4477  RDU  N11121          0  123.0  1042      rdu

### 11 从df中选取‘ time’大于100的数据做为新的df4

In [42]:
df4 = df[df['time'] > 100]
df4.head()

date  hour  minute     dep     arr  dep_delay  arr_delay carrier  \
0  2011/12/1  14.0    31.0  1431.0  1730.0       -4.0       -9.0      XE   
2  2011/12/1  10.0    47.0  1047.0  1429.0       20.0       17.0      XE   
3  2011/12/1  19.0    24.0  1924.0  2234.0       -1.0        1.0      XE   
4  2011/12/1   7.0    18.0   718.0  1105.0       -2.0       -8.0      XE   
7  2011/12/2  10.0    25.0  1025.0  1352.0       -5.0       -2.0      XE   

   flight dest   plane  cancelled   time  dist low_dest  
0    4319  SAV  N11121          0  104.0   851      sav  
2    4434  RIC  N11113          0  146.0  1157      ric  
3    4525  SAV  N11106          0  105.0   851      sav  
4    4602  DTW  N11121          0  139.0  1075      dtw  
7    4366  CLT  N11121          0  120.0   912      clt

### 12 将df3和df4合并为一个dataframe，命名为df5

In [43]:
df5 = pd.concat([df3,df4])
print('before:',df3.shape,df4.shape,'after:',df5.shape)
df5.head()

before: (43, 15) (85, 15) after: (128, 15)


date  hour  minute     dep     arr  dep_delay  arr_delay carrier  \
2   2011/12/1  10.0    47.0  1047.0  1429.0       20.0       17.0      XE   
4   2011/12/1   7.0    18.0   718.0  1105.0       -2.0       -8.0      XE   
10  2011/12/2   7.0    13.0   713.0  1058.0       -2.0       -6.0      XE   
14  2011/12/3  19.0     1.0  1901.0  2230.0       -1.0      -14.0      XE   
16  2011/12/4  16.0     8.0  1608.0  2004.0       18.0       40.0      XE   

    flight dest   plane  cancelled   time  dist low_dest  
2     4434  RIC  N11113          0  146.0  1157      ric  
4     4602  DTW  N11121          0  139.0  1075      dtw  
10    4501  PIT  N11107          0  146.0  1117      pit  
14    4509  RIC  N11113          0  134.0  1157      ric  
16    4477  RDU  N11121          0  123.0  1042      rdu

### 13 取出df3中的‘ time’,‘dist’ 这两列做为df6， 
### 求出df6中每列中最大值与最小值的差值（运用lambda函数的方式进行求解 ）

In [44]:
df6 = df3[['time','dist']]
df6.apply(lambda x:max(x)-min(x))

time     41.0
dist    186.0
dtype: float64

### 14 将df按“ dest”分组，统计各目的地有多少条数据，命名为“ dest_count”
###      然后将“ dest”和“ dest_count”组成新的dataframe命名为df7

In [45]:
dest_count = pd.DataFrame(df.groupby('dest').size().reset_index())
df7 = pd.merge(pd.DataFrame(df['dest']),dest_count).drop_duplicates()
df7
# 等价表达
# df7 = pd.DataFrame(df.groupby('dest').size()) # 此时已经自带统计信息，改列名后可直接使用
# df7.columns = ['dest_count']
# df7 

dest   0
0    SAV   5
5    LRD   6
11   RIC   7
18   DTW   5
23   BNA   7
30   CLT   8
38   MCI   7
45   BHM   6
51   PIT   7
58   CRW   2
60   MEM   1
61   CHS   7
68   DSM   1
69   RDU   5
74   XNA   2
76   MSP   9
85   ABQ   4
89   CRP   1
90   OMA   5
95   GRR   4
99   LEX   4
103  CID   6
109  HOB   5
114  HSV   3
117  JAX  10
127  LFT   4
131  CAE   2
133  HRL   1
134  PHX   3
137  SHV   1
138  TYS   3
141  GSP   1
142  BTR   2
144  ATL   5
149  GJT   2
151  VPS   3
154  TUS   1
155  BRO   2
157  STL   2
159  GPT   2
161  TUL   1
162  SLC   1
163  IAD   2
165  ICT   1
166  ORD   2
168  AEX   1
169  COS   1
170  IND   2
172  PBI   1
173  MFE   1

### 15 根据dep_delay不为0，统计df中有多少次航班起飞延误

In [46]:
df[df['dep_delay'] != 0].shape[0]

162

### 16 利用plane字段，统计df中不同航班的飞行次数，以plane和plane_cout格式保存为df8

In [47]:
df8 = pd.DataFrame(df.groupby('plane').size())
df8.columns = ['plane_count']
df8

plane_count
plane              
N0EGMQ            2
N10156           20
N11106           25
N11107           34
N11109           15
N11113           31
N11119           15
N11121           32

### 17 利用carrier字段，计算df中carrier字段不同属性数据的数据量的比值（如：XE的数据量与MQ的数据量的比值）

In [48]:
carrier_group_size = df.groupby('carrier').size()
# 如果多于2个，让所有属性数据进行相互比较，获取字段下所有值间的比值
dic = dict(carrier_group_size)
print(dic)
while dic:
    pi = dic.popitem()
    for k,v in dic.items():
        print(pi[0],':',k,'=',pi[1]/v)

{'MQ': 2, 'XE': 172}
XE : MQ = 86.0


### 18 分别将df7和 df8保存到本地文件，文件名分别为df7.csv和df8.csv

In [49]:
df7.to_csv('df7.csv')
df8.to_csv('df8.csv')